# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e85ba33c64dc6c5942bde0b93bf0d4c15676a7f36a4d8510655fee894af75ef298364004f720b57c9254f0ca8b86da00829ef245ece83d3d40f6057a7e3d63

test:
  secret_key_base: 78ead9ba31e8cefccd46c5c1736213af859622d486bbbbe0581f63a9b66120a75267bd6afd936664ca0991280ecf53b96c5b55c91dc83ae13ba03a02c07ab0de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
